# Generated by Django 5.2.8 on 2025-11-28 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sultan', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='categories/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='products/%Y/%m/%d/', verbose_name='Главное изображение'),
        ),
    ]
